[env:atmega328pb_bare]
platform = atmelavr
board = ATmega328PB

board_build.mcu = atmega328pb
board_build.f_cpu = 8000000L

; jeśli programujesz przez ISP:
upload_protocol = stk500v2
upload_port = COM3
upload_speed = 115200
upload_flags =
    -e
; albo np. avrisp, atmelice_isp itd.
